import random


def configure_transaction_configuration(transaction_type, base_transaction):
    if transaction_type == 'ADD_MONEY_FROM_BANK':
        base_transaction.update({
            'sender_account_type': random.choice(['WALLET_AUTHORITY']),
            'receiver_account_type': random.choice(['CUSTOMER', 'MERCHANT', 'AGENT']),
            'depositor_running_balance': None,
            'dispute_remarks': None,
            'dispute_status': None,
            'original_transaction_reference_for_reversal': None,
            'receiver_credit_amount': None,
            'sender_debit_amount': None,
            'sender_idp_id': None,
            'transaction_id': None,
            'user_note': None,
            'withdrawer_running_balance': None,
            'workflow_request_id': None,
            'transaction_category_id': None,
            'sender_country_code': None,
            'sender_phone_number': None,
            'transaction_reference': None,
            'branch_id': None,
            'merchant_id': None,
            'reversed_transaction_ref': None,
            'fee_payer': None,
            'vat_payer': None,
            'fee_description': None,
            'fee_payer_internal_account': None,
            'vat_payer_internal_account': None,
            'subsidy_id': None,
            'subsidy_amount': None,
            'subsidy_type': None,
            'incentive_payment_type': None,
            'incentive_amount': None,
        })
    if transaction_type == 'ADD_MONEY_FROM_CARD':
        base_transaction.update({
            'sender_account_type': random.choice(['WALLET_AUTHORITY']),
            'receiver_account_type': random.choice(['CUSTOMER', 'MERCHANT', 'AGENT']),
            'bank_transaction_reference': None,
            'dispute_remarks': None,
            'dispute_status': None,
            'original_transaction_reference_for_reversal': None,
            'sender_idp_id': None,
            'user_note': None,
            'workflow_request_id': None,
            'transaction_category_id': None,
            'sender_country_code': None,
            'sender_phone_number': None,
            'branch_id': None,
            'merchant_id': None,
            'reversed_transaction_ref': None,
            'fee_payer': None,
            'vat_payer': None,
            'subsidy_id': None,
            'subsidy_amount': None,
            'subsidy_type': None,
            'incentive_payment_type': None,
            'incentive_amount': None
        })
    if transaction_type == 'SEND_MONEY':
        base_transaction.update({
            'sender_account_type': random.choice(['CUSTOMER']),
            'receiver_account_type': random.choice(['CUSTOMER']),
            'bank_transaction_reference': None,
            'dispute_remarks': None,
            'dispute_status': None,
            'original_transaction_reference_for_reversal': None,
            'request_id': None,
            'workflow_request_id': None,
            'transaction_category_id': None,
            'sender_country_code': None,
            'sender_phone_number': None,
            'branch_id': None,
            'merchant_id': None,
            'reversed_transaction_ref': None,
            'fee_payer': None,
            'vat_payer': None,
            'subsidy_id': None,
            'subsidy_amount': None,
            'subsidy_type': None,
            'incentive_payment_type': None,
            'incentive_amount': None
        })
    if transaction_type == 'MERCHANT_PAYMENT':
        base_transaction.update({
            'sender_account_type': random.choice(['CUSTOMER']),
            'receiver_account_type': random.choice(['MERCHANT']),
            'bank_transaction_reference': None,
            'dispute_remarks': None,
            'dispute_status': None,
            'original_transaction_reference_for_reversal': None,
            'receiver_idp_id': None,
            'request_id': None,
            'workflow_request_id': None,
            'transaction_category_id': None,
            'sender_country_code': None,
            'sender_phone_number': None,
            'branch_id': None,
            'reversed_transaction_ref': None,
            'fee_payer': None,
            'vat_payer': None,
            'fee_description': None,
            'fee_payer_internal_account': None,
            'vat_payer_internal_account': None,
            'subsidy_id': None,
            'subsidy_type': 'NO_SUBSIDY',
            'incentive_payment_type': None,
            'incentive_amount': 0,
        })
    if transaction_type == 'MERCHANT_PAYMENT_REFUND':
        base_transaction.update({
            'sender_account_type': random.choice(['MERCHANT']),
            'receiver_account_type': random.choice(['CUSTOMER']),
            'bank_transaction_reference': None,
            'dispute_remarks': None,
            'dispute_status': None,
            'original_transaction_reference_for_reversal': None,
            'request_id': None,
            'workflow_request_id': None,
            'transaction_category_id': None,
            'sender_country_code': None,
            'sender_phone_number': None,
            'branch_id': None,
            'reversed_transaction_ref': None,
            'fee_payer': None,
            'vat_payer': None,
            'fee_description': None,
            'fee_payer_internal_account': None,
            'vat_payer_internal_account': None,
            'subsidy_id': None,
            'subsidy_amount': None,
            'subsidy_type': None,
            'incentive_payment_type': None,
            'incentive_amount': None,
        })
    if transaction_type == 'CASH_IN':
        base_transaction.update({
            'sender_account_type': random.choice(['AGENT']),
            'receiver_account_type': random.choice(['CUSTOMER']),
            'bank_transaction_reference': None,
            'dispute_remarks': None,
            'dispute_status': None,
            'original_transaction_reference_for_reversal': None,
            'user_note': None,
            'workflow_request_id': None,
            'transaction_category_id': None,
            'branch_id': None,
            'merchant_id': None,
            'reversed_transaction_ref': None,
            'fee_payer': None,
            'vat_payer': None,
            'subsidy_id': None,
            'subsidy_amount': None,
            'subsidy_type': None,
            'incentive_payment_type': None,
            'incentive_amount': None
        })
    if transaction_type == 'CASH_OUT':
        base_transaction.update({
            'sender_account_type': random.choice(['CUSTOMER']),
            'receiver_account_type': random.choice(['AGENT']),
            'bank_transaction_reference': None,
            'dispute_remarks': None,
            'dispute_status': None,
            'original_transaction_reference_for_reversal': None,
            'user_note': None,
            'workflow_request_id': None,
            'transaction_category_id': None,
            'vat_amount': 0,
            'branch_id': None,
            'merchant_id': None,
            'reversed_transaction_ref': None,
            'fee_payer': None,
            'vat_payer': None,
            'subsidy_id': None,
            'subsidy_amount': None,
            'subsidy_type': None,
            'incentive_payment_type': None,
            'incentive_amount': None
        })
    if transaction_type == 'WALLET_TO_BANK':
        base_transaction.update({
            'sender_account_type': random.choice(['CUSTOMER', 'MERCHANT', 'AGENT', 'ORGANIZATION']),
            'receiver_account_type': random.choice(['BANK']),
            'bank_transaction_reference': None,
            'dispute_remarks': None,
            'dispute_status': None,
            'original_transaction_reference_for_reversal': None,
            'receiver_idp_id': None,
            'user_note': None,
            'workflow_request_id': None,
            'transaction_category_id': None,
            'receiver_country_code': None,
            'receiver_phone_number': None,
            'branch_id': None,
            'merchant_id': None,
            'reversed_transaction_ref': None,
            'fee_payer': None,
            'vat_payer': None,
            'subsidy_id': None,
            'subsidy_amount': None,
            'subsidy_type': None,
            'incentive_payment_type': None,
            'incentive_amount': None
        })
    if transaction_type == 'BANK_PARKING_TO_BANK_TRANSFER':
        base_transaction.update({
            'sender_account_type': random.choice(['PARKING']),
            'receiver_account_type': random.choice(['CUSTOMER', 'MERCHANT', 'AGENT', 'ORGANIZATION']),
            'bank_transaction_reference': None,
            'dispute_remarks': None,
            'dispute_status': None,
            'from_account': None,
            'original_transaction_reference_for_reversal': None,
            'receiver_idp_id': None,
            'sender_idp_id': None,
            'to_account': None,
            'user_note': None,
            'workflow_request_id': None,
            'transaction_category_id': None,
            'receiver_country_code': None,
            'receiver_phone_number': None,
            'sender_country_code': None,
            'sender_phone_number': None,
            'branch_id': None,
            'merchant_id': None,
            'reversed_transaction_ref': None,
            'fee_payer': None,
            'vat_payer': None,
            'fee_description': None,
            'fee_payer_internal_account': None,
            'vat_payer_internal_account': None,
            'subsidy_id': None,
            'subsidy_amount': None,
            'subsidy_type': None,
            'incentive_payment_type': None,
            'incentive_amount': None
        })
    if transaction_type == 'BRANCH_TO_MERCHANT':
        base_transaction.update({
            'sender_account_type': random.choice(['MERCHANT']),
            'receiver_account_type': random.choice(['MERCHANT']),
            'bank_transaction_reference': None,
            'dispute_remarks': None,
            'dispute_status': None,
            'original_transaction_reference_for_reversal': None,
            'receiver_idp_id': None,
            'user_note': None,
            'workflow_request_id': None,
            'transaction_category_id': None,
            'receiver_country_code': None,
            'receiver_phone_number': None,
            'sender_country_code': None,
            'sender_phone_number': None,
            'reversed_transaction_ref': None,
            'fee_payer': None,
            'vat_payer': None,
            'subsidy_id': None,
            'subsidy_amount': None,
            'subsidy_type': None,
            'incentive_payment_type': None,
            'incentive_amount': None
        })
    if transaction_type == 'MERCHANT_GATEWAY_TRANSACTION':
        base_transaction.update({
            'sender_account_type': random.choice(['CUSTOMER']),
            'receiver_account_type': random.choice(['MERCHANT']),
            'bank_transaction_reference': None,
            'dispute_remarks': None,
            'dispute_status': None,
            'original_transaction_reference_for_reversal': None,
            'receiver_idp_id': None,
            'workflow_request_id': None,
            'transaction_category_id': None,
            'reversed_transaction_ref': None,
            'fee_payer': None,
            'vat_payer': None,
            'fee_description': None,
            'fee_payer_internal_account': None,
            'vat_payer_internal_account': None,
            'subsidy_id': None,
            'subsidy_amount': None,
            'subsidy_type': None,
            'incentive_payment_type': None,
            'incentive_amount': None
        })
    if transaction_type == 'AGENT_ADD_FUND':
        base_transaction.update({
            'receiver_account_type': random.choice(['AGENT']),
            'sender_account_type': random.choice(['WALLET_AUTHORITY']),
            'bank_transaction_reference': None,
            'dispute_remarks': None,
            'dispute_status': None,
            'original_transaction_reference_for_reversal': None,
            'receiver_idp_id': None,
            'to_account': None,
            'user_note': None,
            'workflow_request_id': None,
            'transaction_category_id': None,
            'receiver_country_code': None,
            'receiver_phone_number': None,
            'branch_id': None,
            'merchant_id': None,
            'reversed_transaction_ref': None,
            'fee_payer': None,
            'vat_payer': None,
            'subsidy_id': None,
            'subsidy_amount': None,
            'subsidy_type': None,
            'incentive_payment_type': None,
            'incentive_amount': None,
        })
    if transaction_type == 'AGENT_FLOAT_COLLECTION':
        base_transaction.update({
            'sender_account_type': random.choice(['AGENT']),
            'receiver_account_type': random.choice(['WALLET_AUTHORITY']),
            'bank_transaction_reference': None,
            'dispute_remarks': None,
            'dispute_status': None,
            'from_account': None,
            'original_transaction_reference_for_reversal': None,
            'sender_idp_id': None,
            'to_account': None,
            'user_note': None,
            'workflow_request_id': None,
            'transaction_category_id': None,
            'sender_country_code': None,
            'sender_phone_number': None,
            'branch_id': None,
            'merchant_id': None,
            'reversed_transaction_ref': None,
            'fee_payer': None,
            'vat_payer': None,
            'subsidy_id': None,
            'subsidy_amount': None,
            'subsidy_type': None,
            'incentive_payment_type': None,
            'incentive_amount': None
        })
    if transaction_type == 'SUBSIDY_RESERVE_PAYMENT':
        base_transaction.update({
            'sender_account_type': random.choice(['ORGANIZATION']),
            'receiver_account_type': random.choice(['WALLET_AUTHORITY']),
            'bank_transaction_reference': None,
            'dispute_remarks': None,
            'dispute_status': None,
            'original_transaction_reference_for_reversal': None,
            'receiver_idp_id': None,
            'request_id': None,
            'user_note': None,
            'workflow_request_id': None,
            'transaction_category_id': None,
            'receiver_country_code': None,
            'receiver_phone_number': None,
            'sender_country_code': None,
            'sender_phone_number': None,
            'branch_id': None,
            'merchant_id': None,
            'reversed_transaction_ref': None,
            'fee_description': None,
            'subsidy_id': None,
            'subsidy_amount': None,
            'subsidy_type': None,
            'incentive_payment_type': None,
            'incentive_amount': None
        })
    if transaction_type == 'SUBSIDY_RELEASE_PAYMENT':
        base_transaction.update({
            'sender_account_type': random.choice(['WALLET_AUTHORITY']),
            'receiver_account_type': random.choice(['ORGANIZATION']),
            'bank_transaction_reference': None,
            'dispute_remarks': None,
            'dispute_status': None,
            'original_transaction_reference_for_reversal': None,
            'receiver_idp_id': None,
            'request_id': None,
            'sender_idp_id': None,
            'user_note': None,
            'workflow_request_id': None,
            'transaction_category_id': None,
            'receiver_country_code': None,
            'receiver_phone_number': None,
            'sender_country_code': None,
            'sender_phone_number': None,
            'branch_id': None,
            'merchant_id': None,
            'reversed_transaction_ref': None,
            'fee_description': None,
            'subsidy_id': None,
            'subsidy_amount': None,
            'subsidy_type': None,
            'incentive_payment_type': None,
            'incentive_amount': None
        })
    if transaction_type == 'SUBSIDY_CASHBACK_PAYMENT':
        base_transaction.update({
            'sender_account_type': random.choice(['WALLET_AUTHORITY']),
            'receiver_account_type': random.choice(['CUSTOMER']),
            'bank_transaction_reference': None,
            'dispute_remarks': None,
            'dispute_status': None,
            'original_transaction_reference_for_reversal': None,
            'request_id': None,
            'sender_idp_id': None,
            'user_note': None,
            'workflow_request_id': None,
            'transaction_category_id': None,
            'receiver_country_code': None,
            'receiver_phone_number': None,
            'sender_country_code': None,
            'sender_phone_number': None,
            'branch_id': None,
            'merchant_id': None,
            'reversed_transaction_ref': None,
            'fee_payer': None,
            'vat_payer': None,
            'fee_description': None,
            'fee_payer_internal_account': None,
            'vat_payer_internal_account': None,
            'incentive_payment_type': None,
            'incentive_amount': None
        })
    if transaction_type == 'SUBSIDY_DIRECT_DISBURSEMENT':
        base_transaction.update({
            'sender_account_type': random.choice(['WALLET_AUTHORITY']),
            'receiver_account_type': random.choice(['CUSTOMER']),
            'bank_transaction_reference': None,
            'dispute_remarks': None,
            'dispute_status': None,
            'original_transaction_reference_for_reversal': None,
            'request_id': None,
            'user_note': None,
            'workflow_request_id': None,
            'transaction_category_id': None,
            'sender_country_code': None,
            'sender_phone_number': None,
            'branch_id': None,
            'merchant_id': None,
            'reversed_transaction_ref': None,
            'fee_description': None,
            'incentive_payment_type': None,
            'incentive_amount': None
        })
    if transaction_type == 'CHARITY_PAYMENT':
        base_transaction.update({
            'sender_account_type': random.choice(['CUSTOMER']),
            'receiver_account_type': random.choice(['ORGANIZATION']),
            'bank_transaction_reference': None,
            'dispute_remarks': None,
            'dispute_status': None,
            'original_transaction_reference_for_reversal': None,
            'workflow_request_id': None,
            'transaction_category_id': None,
            'reversed_transaction_ref': None,
            'fee_payer': None,
            'vat_payer': None,
            'subsidy_id': None,
            'subsidy_amount': None,
            'subsidy_type': None,
            'incentive_payment_type': None,
            'incentive_amount': None
        })
    if transaction_type == 'HELPING_HAND_CREATION_FEE':
        base_transaction.update({
            'sender_account_type': random.choice(['ORGANIZATION']),
            'bank_transaction_reference': None,
            'dispute_remarks': None,
            'dispute_status': None,
            'original_transaction_reference_for_reversal': None,
            'receiver_account_type': None,
            'receiver_idp_id': None,
            'request_id': None,
            'workflow_request_id': None,
            'transaction_category_id': None,
            'receiver_country_code': None,
            'receiver_phone_number': None,
            'sender_country_code': None,
            'sender_phone_number': None,
            'branch_id': None,
            'merchant_id': None,
            'reversed_transaction_ref': None,
            'fee_description': None,
            'subsidy_id': None,
            'subsidy_amount': None,
            'subsidy_type': None,
            'incentive_payment_type': None,
            'incentive_amount': None
        })
    if transaction_type == 'COMMISSION_PAYMENT':
        base_transaction.update({
            'sender_account_type': random.choice(['WALLET_AUTHORITY']),
            'receiver_account_type': random.choice(['AGENT']),
            'bank_transaction_reference': None,
            'dispute_remarks': None,
            'dispute_status': None,
            'original_transaction_reference_for_reversal': None,
            'sender_idp_id': None,
            'workflow_request_id': None,
            'transaction_category_id': None,
            'sender_country_code': None,
            'sender_phone_number': None,
            'branch_id': None,
            'merchant_id': None,
            'reversed_transaction_ref': None,
            'fee_payer': None,
            'vat_payer': None,
            'fee_description': None,
            'subsidy_id': None,
            'subsidy_amount': None,
            'subsidy_type': None,
            'incentive_payment_type': None,
            'incentive_amount': None
        })
    if transaction_type == 'INCENTIVE_PAYMENT':
        base_transaction.update({
            'sender_account_type': random.choice(['WALLET_AUTHORITY']),
            'receiver_account_type': random.choice(['CUSTOMER']),
            'bank_transaction_reference': None,
            'dispute_remarks': None,
            'dispute_status': None,
            'from_account': None,
            'from_account_name': None,
            'original_transaction_reference_for_reversal': None,
            'sender_idp_id': None,
            'workflow_request_id': None,
            'transaction_category_id': None,
            'sender_country_code': None,
            'sender_phone_number': None,
            'branch_id': None,
            'merchant_id': None,
            'reversed_transaction_ref': None,
            'fee_payer': None,
            'vat_payer': None,
            'fee_description': None,
            'subsidy_id': None,
            'subsidy_amount': None,
            'subsidy_type': None,
            'incentive_payment_type': None,
            'incentive_amount': None
        })
    if transaction_type == 'CHARITY_BALANCE_TRANSFER':
        base_transaction.update({
            'sender_account_type': random.choice(['ORGANIZATION']),
            'receiver_account_type': random.choice(['ORGANIZATION']),
            'bank_transaction_reference': None,
            'dispute_remarks': None,
            'dispute_status': None,
            'original_transaction_reference_for_reversal': None,
            'workflow_request_id': None,
            'transaction_category_id': None,
            'reversed_transaction_ref': None,
            'fee_description': None,
            'subsidy_id': None,
            'subsidy_amount': None,
            'subsidy_type': None,
            'incentive_payment_type': None,
            'incentive_amount': None
        })